# Generated by Django 4.1.2 on 2022-10-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderplacementapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='orderfile',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
