# Generated by Django 4.1.2 on 2022-10-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderplacementapi', '0002_customuser_orderfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='orderfile',
            field=models.FileField(upload_to=''),
        ),
    ]
