# Generated by Django 4.1.2 on 2022-10-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderplacementapi', '0004_remove_customuser_orderfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('japan', 'Japan'), ('france', 'France'), ('germany', 'Germany'), ('china', 'China')], default='', max_length=10),
        ),
    ]
