# Generated by Django 4.1.2 on 2022-10-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_masterdocs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='document',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='masterdocs',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
