# Generated by Django 4.1.2 on 2022-10-20 11:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular', models.CharField(default='', max_length=50)),
                ('Ordered_ItemCode', models.CharField(default='', max_length=20)),
                ('Base_ItemCode', models.CharField(default='', max_length=20)),
                ('Qty', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='orderfile',
            field=models.FileField(upload_to=django.core.files.storage.FileSystemStorage()),
        ),
    ]
