# Generated by Django 4.1.2 on 2022-10-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_mastermodel_base_itemcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermodel',
            name='Base_ItemCode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='mastermodel',
            name='Ordered_ItemCode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='mastermodel',
            name='Particular',
            field=models.CharField(default='', max_length=50),
        ),
    ]
